recipeProject/recipeBlog/urls.py
from django.conf.urls import patterns, url
from recipeBlog import views
from recipeBlog.views import RecipeList, RecipeDetail
from recipeBlog.models import Recipe
from django.core.urlresolvers import reverse
from recipeBlog.views import VoteFormView

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^recipe_list/$', RecipeList.as_view(), name='recipe-list'),
        url(r'^recipe/(?P<pk>\d+)$', RecipeDetail.as_view(), name='recipe-detail'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^register/$', views.register, name='register'),
        url(r'^please_sign_up/$', views.please_sign_up, name='please_sign_up'),
        url(r'^recipe_form/$', views.recipe_form, name='recipe_form'),
        url(r'^restricted/$', views.restrict_access, name='restrict_access'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^tag_page/(?P<tag>\w+)$', views.tag_page, name='tag-page'), 
        url(r'^vote/$', views.VoteFormView.as_view(), name='vote'), 
	
        )

recipeProject/recipeProject/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   url(r'^recipeBlog/', include('recipeBlog.urls')),
   url(r'^admin/', include(admin.site.urls)),
   url(r'^comments/', include('django_comments.urls')),

)

recipeProject/recipeBlog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.db.models import Count

# Create your models here.
class  RecipeVoteCountManager(models.Manager):
	def get_query_set(self):
		return super(RecipeVoteCountManager, self).get_query_set().annotate(
			votes = Count('vote')).order_by('-votes')

class  UserProfile(models.Model):
	#This line is required. Links UserProfile to a User model
	user=models.OneToOneField(User)

	# The additional attributes we wish to include.
	picture=models.ImageField(upload_to='profile_images', blank=True)

	# Override the __unicode__() method to return out something meaningful
	def __unicode__(self):
		return self.user.username

class  Recipe(models.Model):
	name = models.CharField(max_length=30, unique=True)
	preparationTime = models.CharField(max_length=20)
	serves = models.CharField(max_length=25)
	description = models.TextField()
	ingredients = models.TextField()
	directions = models.TextField()
	tags = TaggableManager()
	
	recipePicture=models.ImageField(upload_to='recipe_images', blank=True)

	with_votes = RecipeVoteCountManager()
	objects = models.Manager()  #default manager

	def __unicode__(self):
		return self.name

class Vote(models.Model):
	voter = models.ForeignKey(User)
	recipe = models.ForeignKey(Recipe)

	def __unicode__(self):
		return "%s upvoted %s" % (self.voter.username, self.recipe.name)

recipeProject/recipeBlog/forms.py
from recipeBlog.models import UserProfile, Recipe, Vote
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'size':40}), help_text="Please enter a username")
	email = forms.CharField(widget=forms.TextInput(attrs={'size':40}), help_text="Please enter your email")
	password = forms.CharField(widget=forms.PasswordInput(attrs={'size':40}), help_text="Please enter a password")

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):
	picture = forms.ImageField(help_text="Select a profile image to upload.", required=False)

	class Meta:
		model = UserProfile
		fields = ['picture']
			
class RecipeForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={'size':30}), help_text="Name of Recipe")
	preparationTime = forms.CharField(widget=forms.TextInput(attrs={'size':15}), help_text="Preparation Time")
	serves = forms.CharField(widget=forms.TextInput(attrs={'size':15}), help_text="Serves")
	description = forms.CharField(widget=forms.Textarea(attrs={'cols':50, 'rows':6}), help_text="Description of Recipe")
	ingredients = forms.CharField(widget=forms.Textarea(attrs={'cols':50, 'rows':6}), help_text="Ingredients")
	directions = forms.CharField(widget=forms.Textarea(attrs={'cols':50, 'rows':6}), help_text="Directions")
	

	recipePicture = forms.ImageField(help_text="Photo of recipe(Optional)", required=False)
	class Meta:
		model = Recipe
		fields = ['name', 'preparationTime', 'serves', 'description', 'ingredients', 'directions', 'recipePicture', 'tags']

class VoteForm(forms.ModelForm):
	class Meta:
		model = Vote 

recipeProject/recipeBlog/views.py
#from django.shortcuts import HttpResponse
from django.shortcuts import render
from recipeBlog.forms import UserForm, UserProfileForm, RecipeForm, VoteForm
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from recipeBlog.models import Recipe, Vote
from django.views.generic.edit import FormView
from django.contrib.comments.forms import CommentForm
import json

def index(request):
	#return HttpResponse("Out of the pan")
	 # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    context_dict = {'boldmessage': "I am bold font from the context"}

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

    return render(request, 'recipeBlog/index.html', context_dict)

def recipes(request):
	context_dict = {'boldmessage': "I am bold font from the context"}
	return render(request, 'recipeBlog/recipes.html', context_dict)

def register(request):
    context=RequestContext(request)
     
     # A boolean value for telling the template whether the registration was successful.
     # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

     # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user=user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile=profile_form.save(commit=False)
            profile.user=user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture=request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered=True

            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
    else:
        user_form=UserForm()
        profile_form=UserProfileForm()

         # Render the template depending on the context.
    return render_to_response(
            'recipeBlog/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

def please_sign_up(request):
    context_dict = {'boldmessage': "I am bold font from the context"}
    return render(request, 'recipeBlog/please_sign_up.html', context_dict)

def user_login(request):
    # Like before, obtain the context for the user's request.
    context=RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username=request.POST['username']
        password=request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user=authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/recipeBlog/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your OutOfThePan account is disabled!")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

        # The request is not a HTTP POST, so display the login form.
        # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('recipeBlog/login.html', {}, context)

@login_required
def restrict_access(request):
    return HttpResponse("Since you're logged in, you can see this page!")

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    #Take the user back to the homepage
    return HttpResponseRedirect('/recipeBlog/')

def recipe_form(request):
    context=RequestContext(request)

    submitted = False

    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of RecipeForm
        recipe_form=RecipeForm(data=request.POST)

        # If the form is valid...
        if recipe_form.is_valid():
            # Save the user's form data to the database.
            rForm=recipe_form.save()

            # Did the user provide a recipe picture?
            # If so, we need to get it from the input form and put it in the Recipe model.
            if 'recipePicture' in request.FILES:
                profile.picture=request.FILES['recipePicture']

            # Now we save the Recipe model instance.
            rForm.save()

            # Update our variable to tell the template submission was successful.
            submitted=True

            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            # They'll also be shown to the user.
        else:
            print recipe_form.errors

        # Not a HTTP POST, so we render our form using the ModelForm instance.
        # This form will be blank, ready for user input.
    else:
        recipe_form=RecipeForm()

         # Render the template depending on the context.

    return render_to_response('recipeBlog/recipe_form.html', {'recipe_form': recipe_form, 'submitted': submitted}, context)

class RecipeList(ListView):
    model = Recipe
    queryset = Recipe.with_votes.all()
# Showing the voted state:  indication to know if the headline was voted or not. 
#To achieve this, we can pass ids of all the links that have been voted by the 
#logged in user. This can be passed as a context variable i.e. voted.
    def get_context_data(self, **kwargs):
        context = super(RecipeList, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            recipes_in_page = [recipe.id for recipe in context["object_list"]]
            # like intersection of voted recipes and recipe list on that page
            voted = voted.filter(recipe_id__in=recipes_in_page)
            voted = voted.values_list('recipe_id', flat=True)
            context["voted"] = voted
        return context

class RecipeDetail(DetailView):
    model = Recipe
    
def comment(request):
    return HttpResponseRedirect(request.POST['next'])

def tag_page(request, tag):
    recipes = Recipe.objects.filter(tags__name=tag)
    return render_to_response('recipeBlog/tag_page.html', {'recipes':recipes, 'tag':tag})

#We are using a mixin to implement a JSON response for our AJAX requests
class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        # successful then 200 
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        # successful then 200 
        response.status = 200 if valid_form else 500
        return response
        
        #toggle between the situation: if a user hasn't voted previously, allow vote
        # else delete second vote
    def form_valid(self, form):
        recipe = get_object_or_404(Recipe, pk=form.data["recipe"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, recipe=recipe)
        has_voted = (len(prev_votes) > 0)

recipeProject/templates/recipeBlog/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

    <title>Out of the Pan - {% block title %}Food and Cooking{% endblock %}</title>
	</head>

    <body>
    {% block content %}
	
    {% endblock %}

	<div class="footer">
        	<p align="center">Copyright &copy; Out of the Pan 2014</p>
    	</div>
	
    

    	<!-- jQuery -->
    	<script src="{% static 'js/jquery-1.11.1.js' %}"></script>

    	<!-- Bootstrap Core JavaScript -->
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'vote.js' %}"></script>
    </body>
</html>

recipeProject/templates/recipeBlog/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Out of the Pan - Food and Cooking</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">
    <link href="{% static 'css/user.css' %}" rel="stylesheet" type="text/css">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="messages">
         {% if user.is_authenticated %}
         hello {{ user.username }}!
         {% else %}
         hello guest!
         {% endif %}
    </div>
  

    <div class="brand">Out of the Pan</div>
   
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Out of the Pan</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li>
                        <a href="/recipeBlog/">Home</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/recipe_list/">Recipes</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/recipe_form/">Post Recipe</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/logout/">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="/recipeBlog/">Home</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/recipe_list/">Recipes</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/please_sign_up/">Post Recipe</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/register/">Register</a>
                    </li>
                    <li>
                        <a href="/recipeBlog/login/">Login</a>
                    </li>
                {% endif %}   
                </ul>
            </div>
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="{% static 'img/pic-1.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/pic-2.jpg' %}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static 'img/pic-3.jpg' %}" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Out of the Pan</h1>
                    <hr class="tagline-divider">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Hello and welcome to
                        <strong>Out of the Pan</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="{% static 'img/intro-pic.jpg' %}" alt="">
                    <hr class="visible-xs">
                    <p>Thank you for stopping by our website where you can find well-crafted recipes for the home cook.</p>
                    <p>We invite you to try the recipes, and if you would like, leave constructive feedback in the comments. </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Where we get the
                        <strong>recipes</strong>
                    </h2>
                    <hr>
                    <p>We have users registered with us who post recipes they would like to share with our visitors. </p>
                    <p>Want to post a recipe? Yes, you can absolutely do so! :) All you have to do is, click on the Register tab at the top of the page and fill in the details required for registration. That's it! You're now ready to share your talent with the world.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>comments</strong>
                    </h2>
                    <hr>
                    <p>Constructive criticism is welcome. Rude or mean comments are not welcome. Please restrict your comments to the topic at hand, for the benefit of all who may be reading. </p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Out of the Pan 2014</p>
                </div>
            </div>
        </div>
    </footer>



    <!-- jQuery -->
    <script src="{% static 'js/jquery-1.11.1.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

recipeProject/templates/recipeBlog/login.html
{% extends "recipeBlog/base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

    <br/><br/><br/><br/>

    <div class="container">
        <form class="form-signin" id="login_form" method="post" action="/recipeBlog/login/">

        <br/>
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <h2 class="form-heading"> Login</h2>
            {% if bad_details %}
            <p><strong>Your username and/or password was incorrect!</strong></p>
            {% elif disabled_account %}
            <p><strong>Your account is currently disabled, we can't log you in!</strong></p>
            {% endif %}

            {% csrf_token %}
            <p class="para1">Username:
            <br/>
            <input type="text" class="input-block-level" placeholder="Username" name="username" value="" size="35"/> </p>
            
            <p class="para1">Password:
            <br/>
            <input type="password" class="input-block-level" placeholder="Password" name="password" value="" size="35"/> </p>
            
            <br/>

            <button class="btn btn-primary" type="submit">Sign in</button>
        </div>    
        </form>

    </div>

{% endblock %}

recipeProject/templates/recipeBlog/logout.html
<!DOCTYPE html>
<html>
    <head>
       
        <title>Out of the Pan</title>
    </head>

    <body>
        <h1>Logout from 'Out of the Pan'</h1>

        <form id="login_form" method="post" action="/recipeBlog/logout/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

    </body>
</html>

recipeProject/templates/recipeBlog/please_sign_up.html
{% block title %}Restricted!{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>Restricted Page!</h1>

    Since you're either not a user, or haven't signed in, you can't post a recipe!
    <p><a href="{% url 'login' %}">Please sign in.</a></p>
    <p> OR </p>
    <p><a href="{% url 'register' %}">Please register.</a></p>

</div>
{% endblock %}​

recipeProject/templates/recipeBlog/recipe_detail.html
{% extends "recipeBlog/base.html" %}
{% load static %}
{% load comments %}

{% block title %}Recipe Details!{% endblock %}

{% block content %}

<br/><br/><br/><br/>
<div class="container">
<div class="jumbotron">
	
<div class="container">
<h2 class="form-heading"> {{ object.name }}</h2>
<p class="para1">Preparation Time: {{ object.preparationTime }}</p>
<p class="para1">Serves: {{ object.serves }}</p>
<p class="para1">Description: {{ object.description }}</p>
<p class="para1">Ingredients: {{ object.ingredients }}</p>
<p class="para1">Directions: {{ object.directions }}</p>
</div>

<div class="tags">
	{% for tag in recipe.tags.all %}
	<a href="/recipeBlog/tag_page/{{tag}}">{{tag}}</a>
	{% if not forloop.last %}, {% endif %}
	{% endfor %}
</div>

</div>
</div>

<div class="container">
<p><a href="{% url 'recipe-list' %}">Back to food list</a></p>
</div>

<!--Comments-->
{% get_comment_list for recipeBlog.recipe name.id as comment_list %}
<div class="comments">
<h3>Comments</h3>
<div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'recipe-detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p><a href="{% url 'login' %}">Please log in to leave a comment.</a></p>
{% endif %}
  </div>

  {% get_comment_list for recipeBlog.recipe object.id as comment_list %}
  {% for comment in comment_list %}
  <p>Posted by: {{ comment.user_name }} on {{ comment.submit_date }}</p>
  <p>Comment: {{ comment.comment }}</p>
  {% endfor %}

</div>


{% endblock %}

recipeProject/templates/recipeBlog/recipe_form.html
{% extends "recipeBlog/base.html" %}

{% block title %}Post Recipe!{% endblock %}

{% block content %}

	<div class="container">
        {% if submitted %}
        <p>Thank you for submitting your recipe!</p>

        <p><a href="/recipeBlog/">Return to the homepage.</a></p>
        {% else %}

        <form class="form-signin" id="user_form" method="post" action="/recipeBlog/recipe_form/"
              enctype="multipart/form-data">
            {% csrf_token %}
        <br/><br/><br/><br/><br/>

            <div class="col-md-6 col-md-offset-3 jumbotron">
            <h2 class="form-heading">Submit Your Recipe</h2>
            <!-- Display each form here -->
            <p class="para1">
            {% for field in recipe_form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text}}<br/>
            {{ field }}<br/>
            {% endfor %} 
            </p>

            <!-- Provide a button to click to submit the form. -->
            <input class="btn btn-primary" type="submit" name="submit" value="Submit" />
           <!--</p>-->
            </div>
        </form>
        {% endif %}
    </div>


{% endblock %}

recipeProject/templates/recipeBlog/recipe_list.html
{% extends "recipeBlog/base.html" %}
{% load comments %}
{% block title %}Recipe list!{% endblock %}

{% block content %}

    <p class="para1">
    <h1>List of recipes!</h1>

    <ol>
    {% for name in object_list %}
    <form method="post" action="{% url 'vote' %}" class="vote_form">
    <li> [ {{ name.votes }} ] <!--Display no. of votes -->
    {% csrf_token %}
    <input type="hidden" id="id_recipe" name="recipe" class="hidden_id" value="{{ recipe.pk }}" /> <!-- recipe id taken from for-loop -->
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" /> <!-- currently logged in user -->
    {% if not user.is_authenticated %}
    <button disabled title="Please login to vote">+</button>
    {% elif recipe.pk not in voted %}
    <button>+</button> <!--button for voting -->
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{% url 'recipe-detail' pk=name.id %}">{{ name.name }}</a>
        {% get_comment_count for recipeBlog.recipe name.id as comment_count %}
    <!-- if comment_count>1 then Comment(s) -->
    <p class="details">{{ comment_count }} Comment{{comment_count|pluralize }}</a></p>
    </li>
    {% endfor %}
    </ol>

    <p><b> Want to add a recipe? </b></p>
    <a href="{% url 'login' %}">Login</a> OR <a href="{% url 'register' %}">Register</a>
    </p>


{% endblock %}

recipeProject/templates/recipeBlog/restricted.html
{% block title %}Restricted!{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>Restricted Page!</h1>

    Since you're logged in, you can see this page!

</div>
{% endblock %}

recipeProject/templates/recipeBlog/tag_page.html
{% extends "recipeBlog/base.html" %}

{% block content %}
<h2>Recipes tagged: {{tag}}</h2>

{% for recipe in recipes %}
<p>{{recipe.submit_date}}:<a href="/recipeBlog/recipe/{{recipe.id}}">{{ recipe.name }}</a></p>

{% endfor %}
{% endblock %}